name: Publish

on:
  push:
    branches:
    - initial
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      with:
        submodules: false

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2.4.1
      env: ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      with:
        hugo-version: '0.68.3'
        extended: true

    - name: Build site
      run: hugo --minify --debug

    - name: FTP site
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server:  puk-bornesulinowo.home.pl
        username: www
        password: ${{ secrets.FTP_PASSWORD_PUK }}
        local-dir: ./public/
        server-dir: public_html/
        exclude: .htaccess  
          -  **/.htaccess/**
          - '*.mp4'
          - '*.webm'
          - '*.js'
          - '*.css'

