name: Publish

on:
  push:
    branches:
    - initial
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1
      with:
        submodules: false

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.68.3'
        extended: true

    - name: Build site
      run: hugo --minify

    - name: FTP site
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server:  puk-bornesulinowo.home.pl/public_html/
        username: www
        password: ${{ secrets.FTP_PASSWORD_PUK }}
        local-dir: public/
        exclude: .htaccess  
          -  **/.htaccess/**

