name: Publish

on:
  push:
    branches:
    - initial

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1
      with:
        submodules: false


    - name: Deploy
      uses: SamKirkland/FTP-Deploy-Action@3.0.0
      with:
        ftp-server:  puk-bornesulinowo.home.pl/public_html/
        ftp-username: www
        ftp-password: ${{ secrets.FTP_PASSWORD_PUK }}
        local-dir: ./public/
