name: Publish

on:
  push:
    branches:
    - initial

jobs:
  Deploy:
    runs-on: ubuntu-20.04
    steps:

    - uses: actions/checkout@v2
      with:
        submodules: false

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.68.3'

    - name: Build
      run: hugo

    - name: Deploy
      uses: SamKirkland/FTP-Deploy-Action@3.0.0
      with:
        ftp-server:  puk-bornesulinowo.home.pl/public_html/
        ftp-username: www
        ftp-password: ${{ secrets.FTP_PASSWORD_PUK }}
        local-dir: ./public/
